### ISSUE TITLE
view3dscene_3.18.0 screenshots/videos from command-line-interface still jagged

### ISSUE THREAD

**Issue by ghost** [castle-engine/view3dscene#10] opened 2018-12-13 17:47 UTC

**Comment by michaliskambi** [comment] 2019-01-08 18:44
Hi,

Sorry for the delay -- I simply didn't find the time to investigate this in December. I had too many tasks I promised to finish in 2018 :)

I see that you have edited the description to be empty, and closed the issue. I hope that this means that you have rechecked this and it turns out OK. In general, there's no need to edit the description to be empty in this case :)

Regards,
Michalis

**Comment by elmkni** [comment] 2019-08-04 18:29
Michalis said:

"I'll look into it, of course, as soon as I'll find the time."
"I can promise I'll get to this task, and fix it"

My question after 7 month of waiting: 

"How soon can you fix it?"

Fixing the bug has high priority for me.

I want to be able to make anti-aliased snapshots from the 
commandline with higher resolutions than my pc-monitor.

With best regards, Elmar.

**Comment by michaliskambi** [comment] 2019-08-05 07:43
Both issues are now fixed:

- `view3dscene --anti-alias 6 --screenshot 12 test.png test.x3dv` uses anti-aliasing correctly, result below.

- and `view3dscene --help` shows a message using a different UI, with a scrollbar, so it will fit on screen.

![test2](https://user-images.githubusercontent.com/1076978/62447365-84da7500-b765-11e9-880f-eb642cf214c2.png)

**Comment by michaliskambi** [comment] 2019-08-05 07:46
P.S. A version with a fix will be automatically available within ~15 minutes on http://michalis.ii.uni.wroc.pl/view3dscene-snapshots/ .

**Comment by elmkni** [comment] 2019-08-05 09:53
Dear Michalis,

thank you very much -- that's what I have been waiting for!

Finally I can make anti-aliased movies with X3D via a batch-file
from the command line with view3dscene and ffmpeg! -- Super!!!

Also the help-screen now shows up completely and scrollable -- cool!
But how do I send its contents to the clipboard? -- Could that be added?

With best regards,

Elmar

**Comment by michaliskambi** [comment] 2019-08-05 11:04
> But how do I send its contents to the clipboard? -- Could that be added?

Sure, done.

Note that all the command-line options are also documented in more details on https://castle-engine.io/view3dscene.php#section_command_line_options .

**Closed by michaliskambi** 2019-08-05 11:04 UTC

**Comment by elmkni** [comment] 2019-08-05 17:30
Hi Michalis,

you have added a 'copy to clipboard'-button to the help menu, 
but it does not work on MS-Windows version 10.0.18362.239! 

Only 'ctrl-c' via keyboard works.

Please fix!

With best regards,

Elmar

**Comment by michaliskambi** [comment] 2019-08-06 09:16
> Only 'ctrl + c' via keyboard works.

Ups, indeed I forgot to assign the appropriate action when the "Copy to clipboard" button is just clicked. Thanks, fixed.

> A left-click with the mouse on the canvas closes help-view: is that intended?

This was intended, But since it seems non-intuitive, I removed it.

**Comment by elmkni** [comment] 2019-08-06 09:31
Hi Michalis,

Thanks a lot for the fix!

Elmar
